version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      vite:
        patterns:
          - "@vitejs/plugin-react"
          - "esbuild"
          - "vite"
